### ISSUE TITLE
Database migration triggers dupilicate collumn

### ISSUE THREAD

**Issue by vanlooverenkoen** [simolus3/moor#1313]
We just released our first migration but we get a duplicate column name.

```
@UseMoor(tables: [
   ... all my tables
])
class MyDatabase extends _$MyDatabase {
  MyDatabase(QueryExecutor db) : super(db);

  MyDatabase.connect(DatabaseConnection connection) : super.connect(connection);

  @override
  int get schemaVersion => 2;

  @override
  MigrationStrategy get migration => MigrationStrategy(
      onCreate: (m) => m.createAll(),
      onUpgrade: (m, from, to) async {
        print('Migration from $from to $to');
        if (from < 2) {
          await m.createTable(dbNewTable); //new table
          await m.addColumn(dbTableA, dbTableA.newColumn); //add new column to tableA
          await m.addColumn(dbTableB, dbTableB.newColumn);//add new column to tableB
          await m.addColumn(dbTableC, dbTableC.newColumn); //add new column to tableC
          await m.alterTable(TableMigration(dbTableA)); //should change a non nullable field to a nullable field
          await m.alterTable(TableMigration(dbTableB)); //should change a non nullable field to a nullable field
          await m.alterTable(TableMigration(dbTableC)); //should change a non nullable field to a nullable field
          print('Migration < 2 completed');
        }
        print('Migration from $from to $to completed');
      });
}
```

The exception
```
Non-fatal Exception: io.flutter.plugins.firebase.crashlytics.FlutterError: SqliteException(1): duplicate column name: newColumn. Error thrown null.
       at DatabaseImpl.execute(DatabaseImpl.java:119)
       at _VmDelegate._runWithArgs(_VmDelegate.java:193)
       at _VmDelegate.runCustom(_VmDelegate.java:203)
       at _ExecutorWithQueryDelegate.runCustom.<fn>(runCustom.java:85)
       at _ExecutorWithQueryDelegate._synchronized(_ExecutorWithQueryDelegate.java:31)
       at _ExecutorWithQueryDelegate.runCustom(_ExecutorWithQueryDelegate.java:82)
       at ServerImplementation._runQuery(ServerImplementation.java:130)
```

We got around 100k users. But only 100-150 of them have this error. I have no clue what we are doing wrong. I would expect that the `newColumn` would only be created once.

Maybe we should add a synchronized block around the migration? Or is that not the problem?

**Comment by simolus3** [comment]
> Maybe we should add a synchronized block around the migration?

Moor is already doing that by default.

For now, my best guess is that the app might have been killed while a migration was running before. The migration could have been interrupted, causing a state where some `addColumn` calls have already been completed but the `user_version` hasn't been increased yet. In that case, the migration would get called again later, causing the error here.

We can't run migrations in a transaction by default since some pragmas like enabling foreign key constraints don't work when invoked in a transaction. Since your migration doesn't make use of those features, I think you could wrap your `onUpgrade` callback in a `transaction`.

**Comment by vanlooverenkoen** [comment]
So it would be looking like this? 
```
@UseMoor(tables: [
   ... all my tables
])
class MyDatabase extends _$MyDatabase {
  MyDatabase(QueryExecutor db) : super(db);

  MyDatabase.connect(DatabaseConnection connection) : super.connect(connection);

  @override
  int get schemaVersion => 2;

  @override
  MigrationStrategy get migration => MigrationStrategy(
      onCreate: (m) => m.createAll(),
      onUpgrade: (m, from, to) async {
         await transaction(() async {
            print('Migration from $from to $to');
            if (from < 2) {
              await m.createTable(dbNewTable); //new table
              await m.addColumn(dbTableA, dbTableA.newColumn); //add new column to tableA
              await m.addColumn(dbTableB, dbTableB.newColumn);//add new column to tableB
              await m.addColumn(dbTableC, dbTableC.newColumn); //add new column to tableC
              await m.alterTable(TableMigration(dbTableA)); //should change a non nullable field to a nullable field
              await m.alterTable(TableMigration(dbTableB)); //should change a non nullable field to a nullable field
              await m.alterTable(TableMigration(dbTableC)); //should change a non nullable field to a nullable field
              print('Migration < 2 completed');
            }
            print('Migration from $from to $to completed');
        });
      });
}
```

**Comment by simolus3** [comment]
Yes I think that should improve things.

I think this can be reproduced by putting an `await Future.delayed(const Duration(seconds: 30))` somewhere in your migration and stopping your app while it's waiting on that. Without the transaction there might be the problem, with the transaction it should be fixed.

**Comment by vanlooverenkoen** [comment]
Alright thanks. I will try that and keep you posted on the results of this fix.

**Comment by vanlooverenkoen** [comment]
Using the timeout I was able to reproduce the issue. 

Adding the transaction fixed the issue. Thank you so much.

**Comment by FireLizard** [comment]
For me this error still occur. I've wrapped the migration in a transaction like @vanlooverenkoen did.
One can reproduce this when you:

1. remove all data from the android app settings (for fresh installation)
2. rebuild so that `onCreate` are going to be called
3. stop debugging/run-execution
4. increase number of `schemaVersion`
5. rebuild so that `onUpgrade` are going to be called

this migration fails in cause of "[ERROR:flutter/lib/ui/ui_dart_state.cc(198)] Unhandled Exception: SqliteException(1): duplicate column name: newColumn"

Its might already there since the call of `onCreate: (m) => m.createAll()`. What do you think @simolus3 ?

**Comment by FireLizard** [comment]
As a workaround I try-catch that thing and ignore it for now.

Furthermore it seems that under android the feature [Auto Backup](https://developer.android.com/guide/topics/data/autobackup.html) for apps avoids clearing/resetting the database. Because sometimes the migrations runs multiple times. One can disable it in [AndroidManifest](https://stackoverflow.com/a/52421722).

**Comment by simolus3** [comment]
>  One can reproduce this when you:

Can you share the logic of your `onUpgrade` callback? It's true that `onCreate` creates the current version of the schema by default, so your `onUpgrade` logic should be aware of that and check the old schema version to avoid creating a column that you know is already there.

In the steps you shared, it doesn't sound like the problem of a migration finishing half-way occurs.

**Comment by FireLizard** [comment]
Thank you for your reply. Yes, I might check if the column already exists in the first place.

Here is my simple logic:
```dart
class MyDatabase extends _$MyDatabase{
  MyDatabase() : super(_openConnection());

  @override
  int get schemaVersion => 2;

  @override
  MigrationStrategy get migration => MigrationStrategy(
    onCreate: (Migrator m) {
      return m.createAll();
    },
    onUpgrade: (Migrator m, int from, int to) async {
      await transaction(() async {
        // try {
          if (from < 2) {
            await m.addColumn(projects, projects.newColumn);
          }
        // } catch (e) {}
      });
    },
    beforeOpen: (details) async {
      if (details.hadUpgrade && [2].contains(details.versionNow)) {
        await Future.forEach<TableInfo>(allTables, (table) => delete(table).go());
      }
    }  
  );
}
```

**Comment by simolus3** [comment]
Indeed, `createAll()` creates the latest versions of all tables. So if you call it with generated code that has the new column, the new column is going to be there. However, the `onUpgrade` callback won't run in that case (after `onCreate`, the latest schema version is stored in the database. If it's then opened again, drift will notice that it's up to date and _not_ call `onUpgrade`)

If you use that migration with the steps you posted, shouldn't the `if (from < 2)` never trigger? Or was the `schemaVersion` set to `1` in steps 1-3 of your earlier comment?

Of course, if you set the schema version to `1`, create your database (with the column), then bump the schema version again and write an upgrade migration to add the column, the column will be added twice. I'm not sure if that is what you ran into? The idea is to only increase the schema version when there's an actual change to the schema :)
