### ISSUE TITLE
Not Compatible Flutter 1.9

### ISSUE THREAD

**Issue by sunjianan9900** [simolus3/moor#154]
xxx.g.dart :
> _$AppDatabase(QueryExecutor e) : super(const SqlTypeSystem.withDefaults(), e);

**const SqlTypeSystem.withDefaults()** 
Evaluation of this constant expression throws an exception

**Comment by AppleEducate** [comment]
<img width="387" alt="Screen Shot 2019-09-20 at 5 06 03 PM" src="https://user-images.githubusercontent.com/31253215/65358986-15abc980-dbc9-11e9-83da-f6affe624586.png">

Happening on Flutter v1.10 too

**Comment by simolus3** [comment]
I just got a similar problem, but the error eventually resolved itself (probably the Dart analyzer acting up, but I couldn't figure out why). If you hit this again, restarting the IDE or typing in the generated file and then reverting your edits should fix it.

**Comment by rebaz94** [comment]
I have same issue and not resolved until I remove const keyword

**Comment by simolus3** [comment]
Does the problem persist when you [restart the analysis server](https://www.jetbrains.com/help/idea/dart-analysis-tool-window.html#toolbar)? I think this is a bug with Dart tooling, but I can't reproduce this reliably.

**Comment by rebaz94** [comment]
Yes. I restarted the analysis server and also IDE but nothing change.

**Comment by simolus3** [comment]
Can you open a new issue [on the Dart SDK](https://github.com/dart-lang/sdk/issues) and tag me (@simolus3)? I'll reply with some more information, but because

1. it only affects some users
2. sometimes the issue goes away after restarting the analysis sever 
3. it worked on older Dart versions, and there is no changelog entry that would indicate a breaking change that somehow affected this code

I assume that the analyzer is doing something weird here.

**Comment by rebaz94** [comment]
Sure, but before that, I forget to mention that I am using the latest version of flutter. 
here is ```
flutter --version```

```Flutter 1.10.7-pre.78 • channel master • https://github.com/flutter/flutter.git
Framework • revision 839fdbd2ed (15 hours ago) • 2019-09-29 21:32:06 -0700
Engine • revision 5b952f286f
Tools • Dart 2.6.0 (build 2.6.0-dev.0.0 6ff8d2199d)
```

So the issue happens when the flutter on the **master channel** but in stable and dev there is no problem as I changed to stable.

```Flutter 1.9.1+hotfix.2 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 2d2a1ffec9 (3 weeks ago) • 2019-09-06 18:39:49 -0700
Engine • revision b863200c37
Tools • Dart 2.5.0```

**Comment by simolus3** [comment]
Just released a fix in moor and moor_generator 2.0.1. The error should go away after upgrading your packages and re-running the builder.
