### ISSUE TITLE
Merging result sets fails when using LIST subqueries

### ISSUE THREAD

**Issue by frankvollebregt** [simolus3/moor#2278]
When using the Drift `LIST` operator in `.drift` files, Drift fails to merge the resulting classes.
https://drift.simonbinder.eu/docs/using-sql/drift_files/#list-subqueries
```sql
CREATE TABLE books (
  id INT NOT NULL PRIMARY KEY,
  title TEXT NULL,
  group_name TEXT NULL
);

getTitlesWithGroup AS GroupWithTitles: SELECT group_name, LIST(SELECT title FROM books) AS titles FROM books;

getTitlesWithGroupOther AS GroupWithTitles: SELECT group_name, LIST(SELECT title FROM books WHERE title NOT LIKE 'Second%') AS titles FROM books;
```
Ignore the fact that the data model doesn't make sense (group should probably be its own table, etc.). [edit: Since the subquery queries the complete table again, this will definitely not work as intended, but the result remains clear I hope] The two queries both return titles as a `List<String?>`. When running `build_runner`, it outputs
```
 Could not merge result sets to GroupWithTitles: The queries have different columns and types.
```
But when I look at the generated classes, they look as follows:
```dart
class GroupWithTitles {
  final String? groupName;
  final List<String?> titles;
  GroupWithTitles({
    this.groupName,
    required this.titles,
  });
}

class GroupWithTitles {
  final String? groupName;
  final List<String?> titles;
  GroupWithTitles({
    this.groupName,
    required this.titles,
  });
}
```
Meaning that they are indeed identical. I suspect that the `LIST` subqueries are not taken into account while merging the result classes.

**Comment by simolus3** [comment]
Thanks for the report, this should be fixed in ef0cada32e3404a957249e0d5069d0eb6d53e8ba.

**Comment by frankvollebregt** [comment]
I'm trying to override my dependencies to use this new version, but the build runner fails when I run it:
```
[SEVERE] drift_dev:drift_dev on lib/data/database.dart:
Bad state: Too many elements
dart:collection                                                 ListMixin.singleWhere
package:drift_dev/src/analysis/custom_result_class.dart 89:32   transformCustomResultClasses
package:drift_dev/src/backends/build/drift_builder.dart 313:31  _DriftBuildRun._generateMonolithic
package:drift_dev/src/backends/build/drift_builder.dart 150:7   _DriftBuildRun.run
package:drift_dev/src/backends/build/drift_builder.dart 100:5   DriftBuilder.build
```

**Comment by simolus3** [comment]
Do you get the error on the same file that you've posted in the issue description or with different sources? The snippet from this issue works for me now, so there's probably another issue causing the exception.

**Comment by frankvollebregt** [comment]
###
See the below comment for the actual newest findings/issue!

### Update
I just realised that I get the error even when I don't include the SQL above, so there's likely something wrong elsewhere in my code. Is there a way to figure out where/which class causes the error?

### Original Comment
Hi! I just got around to testing this. In my actual app, I use a different (and much too complex for a stand-alone issue) data model. For my app, I have now (temporarily) reverted to just using multiple class names with the same exact properties.

I just upgraded my dependencies and flutter SDK, and when running build_runner I do still get the `Bad State: Too many elements` error, when including the SQL as specified in the orginial issue above
```yaml
drift: ^2.5.0
sqlite3_flutter_libs: ^0.5.12
sqlparser: ^0.27.0

drift_dev: ^2.5.0+1
```
And `flutter --version`:
```
Flutter 3.7.0 • channel stable • https://github.com/flutter/flutter.git
Framework • revision b06b8b2710 (7 days ago) • 2023-01-23 16:55:55 -0800
Engine • revision b24591ed32
Tools • Dart 2.19.0 • DevTools 2.20.1
```
Output:
```
Bad state: Too many elements
dart:collection                                                 ListMixin.singleWhere
package:drift_dev/src/analysis/custom_result_class.dart 88:32   transformCustomResultClasses
package:drift_dev/src/backends/build/drift_builder.dart 318:31  _DriftBuildRun._generateMonolithic
package:drift_dev/src/backends/build/drift_builder.dart 150:7   _DriftBuildRun.run
package:drift_dev/src/backends/build/drift_builder.dart 100:5   DriftBuilder.build
```

**Comment by frankvollebregt** [comment]
Okay, I'll leave the above comment up since the versions are still the same, but I managed to isolate the issue (I think).

If I run the `build_runner` with the below code:
```sql
CREATE TABLE books (
  id INT NOT NULL PRIMARY KEY,
  title TEXT NULL,
  group_name TEXT NULL
);

getTitlesTwice AS TitleList: SELECT LIST(SELECT title FROM books), LIST(SELECT title FROM books) FROM books;
```
It results in the error mentioned before
```
Bad state: Too many elements
dart:collection                                                 ListMixin.singleWhere
package:drift_dev/src/analysis/custom_result_class.dart 88:32   transformCustomResultClasses
package:drift_dev/src/backends/build/drift_builder.dart 318:31  _DriftBuildRun._generateMonolithic
package:drift_dev/src/backends/build/drift_builder.dart 150:7   _DriftBuildRun.run
package:drift_dev/src/backends/build/drift_builder.dart 100:5   DriftBuilder.build
```
If, however, I run the exact same query without specifying the resulting class name (and let it be generated to just be called `GetTitlesTwiceResult`), it _will_ run just fine and output the following class:
```dart
class GetTitlesTwiceResult {
  final List<String?> nestedQuery0;
  final List<String?> nestedQuery1;
  GetTitlesTwiceResult({
    required this.nestedQuery0,
    required this.nestedQuery1,
  });
}
```
I'm not sure what's going on, but I cannot use named result classes and (some combinations of) multiple LIST subqueries together. If you'd rather have this in a separate issue, I can create that too, but I'm not sure how big of an issue this is to resolve.

**Comment by simolus3** [comment]
Thanks for the update. I managed to fix your snippet in f9912d545585af3b8aa667773cbf4f3262cf84f8 - could you check if there are any more problems in your project with that commit?

**Comment by frankvollebregt** [comment]
I just tried the commit with my full project, and I'm happy to report that it all works now! Thank you!

**Comment by simolus3** [comment]
Thanks for the confirmation! I've published `drift_dev: ^2.5.1` which contains the fix.
